# Generated by Django 6.0.4 on 2026-07-01 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('operations', '0003_branch_business'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this member is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='operations.branch'),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='impersonated_by',
            field=models.ForeignKey(blank=True, help_text='Set when owner is impersonating this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonating_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='pin_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Parent role in hierarchy e.g. Manager supervises Receptionist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='staff.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave null for permanent permission', null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max amount for financial permissions e.g. max refund ₦20,000', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='scope',
            field=models.CharField(choices=[('all', 'All Records'), ('own', 'Own Records Only'), ('branch', 'Branch Only')], default='all', help_text='Scope of this permission', max_length=20),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='new_data',
            field=models.JSONField(blank=True, default=dict, help_text='State after the action'),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='object_type',
            field=models.CharField(blank=True, help_text='e.g. Booking, Order, Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='old_data',
            field=models.JSONField(blank=True, default=dict, help_text='State before the action'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='marketplace.business')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff.businessmember')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='businessmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='staff.department'),
        ),
        migrations.CreateModel(
            name='StaffDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='staff.businessmember')),
            ],
            options={
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('emergency', 'Emergency'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='staff_leave_docs/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.businessmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('general', 'General'), ('performance', 'Performance'), ('disciplinary', 'Disciplinary'), ('commendation', 'Commendation'), ('training', 'Training Required'), ('promotion', 'Promotion Candidate'), ('warning', 'Warning')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Private notes only visible to owner/managers')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='staff.businessmember')),
                ('written_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('pin_enabled', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='staff.businessmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('custom', 'Custom')], default='morning', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.businessmember')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_temp_permissions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_permissions', to='staff.businessmember')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_grants', to='staff.permission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('clock_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_device', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='staff.businessmember')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='staff.staffshift')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
