# Generated by Django 6.0.4 on 2026-06-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('rate_to_ngn', models.DecimalField(decimal_places=6, default=1.0, help_text='How many NGN does 1 unit of this currency equal?', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Only one currency should be default (NGN)')),
                ('rate_updated_at', models.DateTimeField(blank=True, null=True)),
                ('auto_update', models.BooleanField(default=True, help_text='Auto-fetch rate from exchange rate API')),
                ('manual_override', models.BooleanField(default=False, help_text='If True, auto-fetch is skipped for this currency')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['-is_default', 'code'],
            },
        ),
    ]
