# Generated by Django 6.0.4 on 2026-06-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate_to_ngn',
            field=models.DecimalField(decimal_places=8, default=1.0, help_text='How many NGN does 1 unit of this currency equal?', max_digits=18),
        ),
    ]
