# Generated by Django 6.0.4 on 2026-06-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_rate_to_ngn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='currency',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='currencies.currency'),
        ),
    ]
