# Generated by Django 6.0.4 on 2026-06-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_remove_currency_name_remove_currency_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
