# Generated by Django 6.0.4 on 2026-06-25 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_remove_currency_currency_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-is_default', '-preferred_currency', 'code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='currency',
            name='convert_from_ngn',
            field=models.DecimalField(decimal_places=8, default=1.0, help_text='How many units of this currency equals 1 NGN?', max_digits=18),
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country this currency belongs to e.g. Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='currency',
            name='preferred_currency',
            field=models.BooleanField(default=False, help_text='Mark as a preferred/featured currency shown prominently in the UI'),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'Auto API'), ('override', 'Manual Override')], default='manual', help_text='How the exchange rate was last set', max_length=20),
        ),
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_to_ngn', models.DecimalField(decimal_places=8, max_digits=18)),
                ('convert_from_ngn', models.DecimalField(decimal_places=8, default=1.0, max_digits=18)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'Auto API'), ('override', 'Manual Override')], default='api', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note about why rate was changed', null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='currencies.currency')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin who set this rate (null if auto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currency Rate History',
                'ordering': ['-created_at'],
            },
        ),
    ]
