# Generated by Django 6.0.4 on 2026-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_shipping_fee_order_business_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
