# Generated by Django 6.0.4 on 2026-07-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_otp_order_delivery_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('transfer', 'Bank Transfer')], default='wallet', max_length=20),
        ),
    ]
