# Generated by Django 6.0.4 on 2026-06-13 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_alter_vehicletype_options_and_more'),
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('orders', '0003_rename_shipping_fee_order_business_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('order', 'Order'), ('delivery', 'Delivery'), ('shipment', 'Shipment'), ('ride', 'Ride'), ('booking', 'Booking'), ('subscription', 'Subscription'), ('other', 'Other')], default='order', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vendor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driver_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('reversed', 'Reversed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('vendor_paid_at', models.DateTimeField(blank=True, null=True)),
                ('driver_paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='marketplace.business')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_commissions', to='drivers.driverprofile')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='commissions.commission')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_type', models.CharField(choices=[('vendor', 'Vendor'), ('driver', 'Driver')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='marketplace.business')),
                ('commissions', models.ManyToManyField(blank=True, related_name='payouts', to='commissions.commission')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to='drivers.driverprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('global', 'Global'), ('industry', 'Per Industry'), ('business', 'Per Business')], default='global', max_length=20)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('percentage_with_min', 'Percentage with Minimum'), ('percentage_with_max', 'Percentage with Maximum'), ('tiered', 'Tiered')], default='percentage', max_length=30)),
                ('platform_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('vendor_rate', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('driver_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('platform_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_platform_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_platform_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('delivery_driver_rate', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('tiered_rates', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='marketplace.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='marketplace.industry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissionrule'),
        ),
    ]
