# Generated by Django 6.0.4 on 2026-06-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_feature_tenantfeature_tenantsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('order', 'Order'), ('delivery', 'Delivery'), ('shipment', 'Shipment'), ('ride', 'Ride'), ('payment', 'Payment'), ('user', 'User'), ('system', 'System'), ('feature', 'Feature'), ('settings', 'Settings'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_url', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='tenancy_act_tenant__d03dbe_idx'), models.Index(fields=['tenant', 'activity_type'], name='tenancy_act_tenant__5e9b80_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user.login', 'User Login'), ('user.logout', 'User Logout'), ('user.register', 'User Register'), ('user.password_change', 'Password Change'), ('tenant.created', 'Tenant Created'), ('tenant.updated', 'Tenant Updated'), ('tenant.suspended', 'Tenant Suspended'), ('tenant.cancelled', 'Tenant Cancelled'), ('member.invited', 'Member Invited'), ('member.joined', 'Member Joined'), ('member.removed', 'Member Removed'), ('member.role_changed', 'Member Role Changed'), ('apikey.created', 'API Key Created'), ('apikey.revoked', 'API Key Revoked'), ('billing.payment', 'Billing Payment'), ('billing.refund', 'Billing Refund'), ('credit.topup', 'Credit Top Up'), ('credit.deduction', 'Credit Deduction'), ('feature.enabled', 'Feature Enabled'), ('feature.disabled', 'Feature Disabled'), ('settings.updated', 'Settings Updated'), ('order.created', 'Order Created'), ('order.cancelled', 'Order Cancelled'), ('order.completed', 'Order Completed'), ('delivery.created', 'Delivery Created'), ('delivery.assigned', 'Delivery Assigned'), ('delivery.completed', 'Delivery Completed'), ('payment.success', 'Payment Success'), ('payment.failed', 'Payment Failed'), ('payment.refunded', 'Payment Refunded'), ('data.export', 'Data Export'), ('data.import', 'Data Import'), ('data.delete', 'Data Delete'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'action'], name='tenancy_aud_tenant__d5375a_idx'), models.Index(fields=['tenant', 'created_at'], name='tenancy_aud_tenant__e03785_idx'), models.Index(fields=['user', 'created_at'], name='tenancy_aud_user_id_4518bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('date', models.DateField()),
                ('total_api_calls', models.IntegerField(default=0)),
                ('successful_api_calls', models.IntegerField(default=0)),
                ('failed_api_calls', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_shipments', models.IntegerField(default=0)),
                ('total_rides', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payments', models.IntegerField(default=0)),
                ('successful_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('credits_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credits_added', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='tenancy_usa_tenant__e510a0_idx'), models.Index(fields=['tenant', 'period'], name='tenancy_usa_tenant__2c0582_idx')],
                'unique_together': {('tenant', 'period', 'date')},
            },
        ),
    ]
