# Generated by Django 6.0.4 on 2026-06-06 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_activityfeed_auditlog_usagemetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('primary', 'Primary Domain'), ('subdomain', 'Subdomain'), ('alias', 'Alias Domain')], default='primary', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verifying', 'Verifying'), ('active', 'Active'), ('failed', 'Verification Failed'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_method', models.CharField(default='dns_txt', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('none', 'No SSL'), ('pending', 'SSL Pending'), ('active', 'SSL Active'), ('expired', 'SSL Expired'), ('failed', 'SSL Failed')], default='none', max_length=20)),
                ('ssl_issued_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('redirect_to_primary', models.BooleanField(default=False)),
                ('force_https', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('check_error', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_domains', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
