# Generated by Django 6.0.4 on 2026-06-30 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_category_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_icons/')),
                ('default_pricing_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('inspection_quote', 'Inspection → Quote'), ('custom_quote', 'Custom Quote'), ('hourly', 'Hourly Rate'), ('daily', 'Daily Rate')], default='inspection_quote', help_text='Default pricing model, providers can override', max_length=20)),
                ('allowed_pricing_types', models.JSONField(default=list, help_text='List of pricing types providers can choose for this service e.g. ["inspection_quote", "custom_quote"]')),
                ('dispatch_type', models.CharField(choices=[('on_demand', 'On-Demand (location-based)'), ('scheduled', 'Scheduled (appointment-based)')], default='on_demand', max_length=20)),
                ('inspection_fee_required', models.BooleanField(default=True, help_text='Customer pays inspection fee before quote')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('individual', 'Individual / Freelancer'), ('business', 'Registered Business')], default='individual', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('operating_address', models.TextField(blank=True)),
                ('operating_radius_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('is_available', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_profiles', to='marketplace.business')),
                ('services', models.ManyToManyField(blank=True, related_name='providers', to='services.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-total_jobs_completed'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('photos', models.JSONField(default=list, help_text='List of uploaded photo URLs')),
                ('video', models.FileField(blank=True, null=True, upload_to='service_request_videos/')),
                ('urgency', models.CharField(choices=[('low', 'Low — Can wait'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location_address', models.TextField()),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — Searching for Provider'), ('accepted', 'Accepted'), ('provider_en_route', 'Provider En Route'), ('inspecting', 'Inspecting'), ('quote_sent', 'Quote Sent'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('in_progress', 'Job In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_provider_found', 'No Provider Found')], default='pending', max_length=30)),
                ('pricing_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('inspection_quote', 'Inspection → Quote'), ('custom_quote', 'Custom Quote'), ('hourly', 'Hourly Rate'), ('daily', 'Daily Rate')], default='inspection_quote', max_length=20)),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspection_fee_paid', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provider_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('inspection_paid', 'Inspection Fee Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.serviceprovider')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True, null=True)),
                ('provider_rating_of_customer', models.IntegerField(blank=True, null=True)),
                ('provider_notes', models.TextField(blank=True, null=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_rating', to='services.servicerequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.TextField(blank=True, help_text='What the provider found during inspection')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_items', models.JSONField(default=list, help_text='Itemized breakdown e.g. [{"name": "Alternator", "cost": 45000}]')),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Customer Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='services.servicerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
