# Generated by Django 6.0.4 on 2026-06-30 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicequote',
            options={'ordering': ['-revision_number', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='review',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='video',
        ),
        migrations.AddField(
            model_name='service',
            name='default_inspection_fee',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='insurance_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_emergency_available',
            field=models.BooleanField(default=False, help_text='Provider handles emergency requests'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='parent_quote',
            field=models.ForeignKey(blank=True, help_text='Previous quote this revises', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='services.servicequote'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='revision_note',
            field=models.TextField(blank=True, help_text='Why this revision was submitted'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='allowed_pricing_types',
            field=models.JSONField(default=list, help_text='Pricing types providers can choose'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_pricing_type',
            field=models.CharField(choices=[('fixed_price', 'Fixed Price'), ('inspection_quote', 'Inspection → Quote'), ('custom_quote', 'Custom Quote'), ('hourly', 'Hourly Rate'), ('daily', 'Daily Rate')], default='inspection_quote', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='inspection_fee_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Customer Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded by Revision'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Set when a provider accepts the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — Searching for Provider'), ('offers_sent', 'Offers Sent to Providers'), ('accepted', 'Accepted by Provider'), ('provider_en_route', 'Provider En Route'), ('inspecting', 'Inspecting'), ('quote_sent', 'Quote Sent'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('in_progress', 'Job In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_provider_found', 'No Provider Found')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='CompletionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before_photos', models.JSONField(default=list, help_text='List of before-job photo URLs')),
                ('after_photos', models.JSONField(default=list, help_text='List of after-job photo URLs')),
                ('completion_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='completion_signatures/')),
                ('notes', models.TextField(blank=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_evidence', to='services.servicerequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. NEMSA Certificate, ASE Mechanic', max_length=255)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(upload_to='provider_certifications/')),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='services.serviceprovider')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('plate_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('warranty_days', models.IntegerField(default=0, help_text='Warranty in days (0 = no warranty)')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_genuine', models.BooleanField(default=True, help_text='Genuine vs. aftermarket part')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='services.servicequote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='service_request_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('provider', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled — Another Provider Accepted')], default='pending', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.serviceprovider')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.servicerequest')),
            ],
            options={
                'ordering': ['distance_km', 'sent_at'],
                'unique_together': {('service_request', 'provider')},
            },
        ),
    ]
