# Generated by Django 6.0.4 on 2026-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicequote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_certification',
            field=models.BooleanField(default=False, help_text='Provider must have at least one verified certification before auto-verification'),
        ),
    ]
