# Generated by Django 6.0.4 on 2026-07-07 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('services', '0003_service_requires_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business that offers this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='marketplace.business'),
        ),
    ]
