# Generated by Django 6.0.4 on 2026-07-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_currency_country_currency_code_and_more'),
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('accepts_online_orders', models.BooleanField(default=True)),
                ('accepts_walk_ins', models.BooleanField(default=True)),
                ('accepts_reservations', models.BooleanField(default=False)),
                ('notify_owner_on_order', models.BooleanField(default=True)),
                ('notify_owner_on_booking', models.BooleanField(default=True)),
                ('notify_owner_sms', models.BooleanField(default=False)),
                ('notify_owner_whatsapp', models.BooleanField(default=True)),
                ('auto_accept_orders', models.BooleanField(default=False, help_text='Automatically confirm incoming orders')),
                ('auto_accept_bookings', models.BooleanField(default=False, help_text='Automatically confirm incoming bookings')),
                ('show_rating', models.BooleanField(default=True)),
                ('allow_reviews', models.BooleanField(default=True)),
                ('settlement_period_days', models.IntegerField(default=1, help_text='Days before earnings are released')),
            ],
            options={
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_above', models.DecimalField(blank=True, decimal_places=2, help_text='Free delivery when order total exceeds this', max_digits=10, null=True)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('estimated_delivery_minutes', models.IntegerField(default=30)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('estimated_pickup_minutes', models.IntegerField(default=15)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allows_scheduled_orders', models.BooleanField(default=False, help_text='Customers can place orders for a future time')),
                ('max_schedule_days_ahead', models.IntegerField(default=7)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('accepts_cash_on_delivery', models.BooleanField(default=False)),
                ('accepts_card', models.BooleanField(default=True)),
                ('accepts_wallet', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Order Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_mobile', models.BooleanField(default=True, help_text='Provider travels to customer')),
                ('is_on_site', models.BooleanField(default=False, help_text='Customer visits provider location')),
                ('operating_radius_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspection_fee_required', models.BooleanField(default=True, help_text='Customer pays inspection fee before quote is generated')),
                ('default_pricing_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('inspection_quote', 'Inspection → Quote'), ('custom_quote', 'Custom Quote'), ('hourly', 'Hourly Rate'), ('daily', 'Daily Rate')], default='inspection_quote', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepts_emergency', models.BooleanField(default=False, help_text='Provider handles emergency requests')),
                ('emergency_surcharge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('response_time_minutes', models.IntegerField(default=30, help_text='Estimated response time in minutes')),
                ('is_insured', models.BooleanField(default=False)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expires_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='businessrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessrole',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessrole',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='businessstaff',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='businessstaff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessstaff',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessstaff',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='businessstaff',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name_plural': 'Businesses'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='accepts_orders',
        ),
        migrations.RemoveField(
            model_name='business',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='business',
            name='delivery_available',
        ),
        migrations.RemoveField(
            model_name='business',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='business',
            name='delivery_radius_km',
        ),
        migrations.RemoveField(
            model_name='business',
            name='delivery_time_minutes',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_open_now',
        ),
        migrations.RemoveField(
            model_name='business',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='business',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='business',
            name='pickup_available',
        ),
        migrations.RemoveField(
            model_name='business',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='business',
            name='working_days',
        ),
        migrations.AddField(
            model_name='business',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Owner manually toggles open/closed'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='document_number',
            field=models.CharField(blank=True, help_text='CAC number, TIN, license number, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='is_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='default_interaction_type',
            field=models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (reservations)'), ('service_requests', 'Service Requests (on-demand)'), ('rides', 'Rides (transport)'), ('mixed', 'Mixed (multiple interaction types)')], default='orders', help_text='How customers interact with businesses in this industry by default', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='custom_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override industry/category commission rate for this specific business', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='marketplace.industry'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — setup incomplete'), ('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('closed', 'Closed Permanently')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='document_type',
            field=models.CharField(choices=[('cac_certificate', 'CAC Certificate'), ('cac_status_report', 'CAC Status Report'), ('tin_certificate', 'TIN Certificate'), ('tax_clearance', 'Tax Clearance'), ('food_license', 'Food Handler License'), ('health_license', 'Health Facility License'), ('business_permit', 'Business Permit'), ('professional_license', 'Professional License'), ('id_card', 'Owner ID Card'), ('utility_bill', 'Utility Bill'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='industry',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or emoji', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='businessdocument',
            unique_together={('business', 'document_type')},
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.TimeField(blank=True, help_text='e.g. 14:00 for hotels', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='e.g. 12:00 for hotels', null=True)),
                ('min_stay_nights', models.IntegerField(default=1, help_text='Minimum nights per booking (hotels)')),
                ('max_stay_nights', models.IntegerField(blank=True, help_text='Maximum nights (null = no limit)', null=True)),
                ('min_advance_hours', models.IntegerField(default=1, help_text='Minimum hours in advance a booking can be made')),
                ('max_advance_days', models.IntegerField(default=365, help_text='How far ahead customers can book')),
                ('cancellation_hours', models.IntegerField(default=24, help_text='Hours before check-in that free cancellation is allowed')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee charged for late cancellation', max_digits=10)),
                ('cancellation_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of booking total charged for late cancellation', max_digits=5)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total required as deposit', max_digits=5)),
                ('requires_guest_kyc', models.BooleanField(default=False, help_text='Guests must complete identity verification before booking')),
                ('max_guests_per_booking', models.IntegerField(blank=True, null=True)),
                ('instant_booking', models.BooleanField(default=True, help_text='Book immediately without host approval')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='marketplace.business')),
            ],
            options={
                'verbose_name_plural': 'Booking Settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/categories/')),
                ('interaction_type', models.CharField(blank=True, choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (reservations)'), ('service_requests', 'Service Requests (on-demand)'), ('rides', 'Rides (transport)'), ('mixed', 'Mixed (multiple interaction types)')], help_text='Leave blank to inherit from industry. Set to override for this category.', max_length=20, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from industry', max_digits=5, null=True)),
                ('has_order_settings', models.BooleanField(default=False, help_text='Businesses in this category can configure order/delivery settings')),
                ('has_booking_settings', models.BooleanField(default=False, help_text='Businesses in this category can configure booking settings')),
                ('has_service_settings', models.BooleanField(default=False, help_text='Businesses in this category can configure service request settings')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('requires_certification', models.BooleanField(default=False, help_text='Businesses must upload certification before activation')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='marketplace.industry')),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'ordering': ['industry', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Sub-category within the industry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='marketplace.businesscategory'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='marketplace_status_0c0fde_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_verified'], name='marketplace_is_veri_6dc5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['industry'], name='marketplace_industr_81bd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city'], name='marketplace_city_id_a65a8f_idx'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_settings', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='marketplace.business'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='BusinessRole',
        ),
        migrations.DeleteModel(
            name='BusinessStaff',
        ),
        migrations.AlterUniqueTogether(
            name='businesscategory',
            unique_together={('industry', 'name')},
        ),
    ]
