# Generated by Django 6.0.4 on 2026-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_businesssettings_ordersettings_servicesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Business Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='businesscategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_booking_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_order_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_service_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (reservations)'), ('service_requests', 'Service Requests (on-demand)'), ('rides', 'Rides (transport)'), ('mixed', 'Mixed (multiple interaction types)')], help_text='Override industry interaction type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='requires_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='industry',
            name='default_interaction_type',
            field=models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (reservations)'), ('service_requests', 'Service Requests (on-demand)'), ('rides', 'Rides (transport)'), ('mixed', 'Mixed (multiple interaction types)')], default='orders', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='businesscategory',
            unique_together={('industry', 'slug')},
        ),
    ]
