# Generated by Django 6.0.4 on 2026-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_businesscategory_interaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='booking_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment / Shortlet'), ('event_center', 'Event Center'), ('resort', 'Resort'), ('guesthouse', 'Guest House'), ('coworking', 'Coworking Space')], default='hotel', max_length=20),
        ),
    ]
