# Generated by Django 6.0.4 on 2026-07-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_bookingsettings_booking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('bookings', 'Bookings'), ('orders', 'Orders'), ('services', 'Services'), ('appointments', 'Appointments'), ('scheduled_services', 'Scheduled Services'), ('rides', 'Rides')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Business Subtype',
                'verbose_name_plural': 'Business Subtypes',
                'ordering': ['interaction_type', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='booking_type',
        ),
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('advance_booking_days', models.IntegerField(default=30)),
                ('buffer_minutes', models.IntegerField(default=0)),
                ('max_concurrent', models.IntegerField(default=1)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancellation_hours', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_settings', to='marketplace.business')),
                ('subtype', models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'appointments'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_businesses', to='marketplace.businesssubtype')),
            ],
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='subtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'bookings'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_businesses', to='marketplace.businesssubtype'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='subtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'orders'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_businesses', to='marketplace.businesssubtype'),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='subtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'services'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_businesses', to='marketplace.businesssubtype'),
        ),
    ]
