# Generated by Django 6.0.4 on 2026-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_businesssubtype_remove_bookingsettings_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubtype',
            name='interaction_type',
            field=models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (transport)'), ('mixed', 'Mixed')], max_length=30),
        ),
    ]
