# Generated by Django 6.0.4 on 2026-07-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_businesssubtype_interaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_type', models.CharField(choices=[('ride_hailing', 'Ride Hailing (Uber-style)'), ('bus', 'Bus / Coach'), ('minibus', 'Minibus / Sprinter'), ('ferry', 'Ferry / Boat'), ('airline', 'Airline'), ('train', 'Train'), ('shuttle', 'Shuttle Service'), ('charter', 'Charter / Hire')], default='ride_hailing', max_length=20)),
                ('fleet_size', models.IntegerField(default=1, help_text='Number of vehicles in fleet')),
                ('operating_cities', models.JSONField(blank=True, default=list, help_text='Cities where service is available')),
                ('operating_radius_km', models.DecimalField(blank=True, decimal_places=2, help_text='Radius for ride-hailing', max_digits=8, null=True)),
                ('allows_advance_booking', models.BooleanField(default=True)),
                ('advance_booking_days', models.IntegerField(default=30)),
                ('min_advance_hours', models.IntegerField(default=1)),
                ('allows_instant_booking', models.BooleanField(default=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_cancellation_minutes', models.IntegerField(default=10, help_text='Minutes after booking that cancellation is free')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accepts_cash', models.BooleanField(default=True)),
                ('accepts_card', models.BooleanField(default=True)),
                ('accepts_wallet', models.BooleanField(default=True)),
                ('accepts_transfer', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('allows_luggage', models.BooleanField(default=True)),
                ('max_luggage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('luggage_fee_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('has_tracking', models.BooleanField(default=False)),
                ('is_insured', models.BooleanField(default=False)),
                ('requires_driver_kyc', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_settings', to='marketplace.business')),
                ('subtype', models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'rides'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_businesses', to='marketplace.businesssubtype')),
            ],
            options={
                'verbose_name_plural': 'Ride Settings',
            },
        ),
    ]
