# Generated by Django 6.0.4 on 2026-07-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_ridesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_type', models.CharField(choices=[('local', 'Local (same city)'), ('interstate', 'Interstate'), ('international', 'International'), ('all', 'All')], default='local', max_length=20)),
                ('operating_cities', models.JSONField(blank=True, default=list, help_text='Cities covered')),
                ('operating_states', models.JSONField(blank=True, default=list, help_text='States covered')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('express_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Express delivery price multiplier', max_digits=4)),
                ('offers_pickup', models.BooleanField(default=True)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('offers_insurance', models.BooleanField(default=False)),
                ('insurance_rate_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='% of declared value charged as insurance fee', max_digits=5)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('max_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('standard_days', models.IntegerField(default=3, help_text='Standard delivery days')),
                ('express_days', models.IntegerField(default=1, help_text='Express delivery days')),
                ('accepts_cash_on_delivery', models.BooleanField(default=False)),
                ('accepts_card', models.BooleanField(default=True)),
                ('accepts_wallet', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('requires_photo', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_settings', to='marketplace.business')),
                ('subtype', models.ForeignKey(blank=True, limit_choices_to={'interaction_type': 'scheduled_services'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_businesses', to='marketplace.businesssubtype')),
            ],
            options={
                'verbose_name_plural': 'Shipment Settings',
            },
        ),
    ]
