# Generated by Django 6.0.4 on 2026-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (on-demand hailing)'), ('transport', 'Transport (scheduled routes & seats)'), ('shipments', 'Shipments (package delivery)'), ('mixed', 'Mixed')], help_text='Override industry interaction type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='default_interaction_type',
            field=models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (on-demand hailing)'), ('transport', 'Transport (scheduled routes & seats)'), ('shipments', 'Shipments (package delivery)'), ('mixed', 'Mixed')], default='orders', max_length=20),
        ),
    ]
