# Generated by Django 6.0.4 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_businesscategory_interaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='has_appointment_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='has_ride_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='has_shippment_settings',
            field=models.BooleanField(default=False),
        ),
    ]
