# Generated by Django 6.0.4 on 2026-07-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_businesscategory_has_appointment_settings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscategory',
            old_name='has_shippment_settings',
            new_name='has_shipment_settings',
        ),
    ]
