# Generated by Django 6.0.4 on 2026-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_rename_has_shippment_settings_businesscategory_has_shipment_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='has_scheduled_service_settings',
            field=models.BooleanField(default=False, help_text='Provider travels to the customer', verbose_name='Scheduled services'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='has_transport_settings',
            field=models.BooleanField(default=False, help_text='Scheduled routes and seat booking', verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_appointment_settings',
            field=models.BooleanField(default=False, help_text='Fixed time slots with a staff member', verbose_name='Appointments'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_booking_settings',
            field=models.BooleanField(default=False, help_text='Rooms, tables, halls — reserving time and space', verbose_name='Bookings'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_order_settings',
            field=models.BooleanField(default=False, help_text='Delivery / pickup of products', verbose_name='Orders'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_ride_settings',
            field=models.BooleanField(default=False, help_text='On-demand vehicle hailing', verbose_name='Rides'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_service_settings',
            field=models.BooleanField(default=False, help_text='Quote-based service requests', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='has_shipment_settings',
            field=models.BooleanField(default=False, help_text='Package delivery and tracking', verbose_name='Shipments'),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (on-demand hailing)'), ('transport', 'Transport (scheduled routes & seats)'), ('shipments', 'Shipments (package delivery)'), ('mixed', 'Mixed')], help_text='The DEFAULT experience — first tab and main CTA. Blank inherits the industry default. This is not the only capability; tick everything offered below.', max_length=32, null=True, verbose_name='Primary interaction'),
        ),
        migrations.AlterField(
            model_name='businesssubtype',
            name='interaction_type',
            field=models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (on-demand hailing)'), ('transport', 'Transport (scheduled routes & seats)'), ('shipments', 'Shipments (package delivery)'), ('mixed', 'Mixed')], max_length=30),
        ),
    ]
