# Generated by Django 6.0.4 on 2026-07-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_businesscategory_has_scheduled_service_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mission',
            field=models.TextField(blank=True, help_text='What the business is trying to do. Optional.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='story',
            field=models.TextField(blank=True, help_text="The business's own account of itself — how it started, what it does. Shown on the About tab.", null=True),
        ),
        migrations.CreateModel(
            name='BusinessContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='marketplace.business')),
            ],
            options={
                'verbose_name': 'Business content block',
                'verbose_name_plural': 'Business content blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='marketplace.business')),
            ],
            options={
                'verbose_name': 'Business FAQ',
                'verbose_name_plural': 'Business FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('cancellation', 'Cancellation'), ('refund', 'Refund'), ('checkin', 'Check-in / Check-out'), ('delivery', 'Delivery'), ('warranty', 'Warranty'), ('house_rules', 'House rules'), ('privacy', 'Privacy'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(help_text='Blank-ish titles help nobody — "Free cancellation up to 24h"', max_length=100)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=8, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='marketplace.business')),
            ],
            options={
                'verbose_name': 'Business policy',
                'verbose_name_plural': 'Business policies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('offer', 'Offer — a deal, discount or bonus'), ('notice', 'Notice — an announcement with no offer attached')], default='offer', max_length=10)),
                ('title', models.CharField(help_text='Short and scannable — "20% off this weekend", "Free delivery"', max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji shown on the strip', max_length=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace/promotions/')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Blank = live immediately', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Blank = runs until switched off. Set this.', null=True)),
                ('cta_label', models.CharField(blank=True, help_text='Optional button text — "Order now", "See rooms"', max_length=40, null=True)),
                ('cta_url', models.CharField(blank=True, help_text='Where the button goes. Relative paths allowed.', max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.business')),
            ],
            options={
                'verbose_name': 'Business promotion',
                'verbose_name_plural': 'Business promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
