# Generated by Django 6.0.4 on 2026-07-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_business_mission_business_story_businesscontentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspromotion',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_promotions', to='marketplace.business'),
        ),
    ]
