# Generated by Django 6.0.4 on 2026-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_businesspromotion_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='services_overview',
            field=models.TextField(blank=True, help_text="For service-type businesses — what you do and how you work. Shown on the About tab. E.g. a mechanic's specialties, a salon's approach, a cleaner's process.", null=True),
        ),
    ]
