# Generated by Django 6.0.4 on 2026-07-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_business_services_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('orders', 'Orders (delivery/pickup)'), ('bookings', 'Bookings (hotels/apartments)'), ('services', 'Service Requests (quote-based)'), ('appointments', 'Appointments (fixed time slots)'), ('scheduled_services', 'Scheduled Services (provider visits customer)'), ('rides', 'Rides (on-demand hailing)'), ('transport', 'Transport (scheduled routes & seats)'), ('shipments', 'Shipments (package delivery)'), ('mixed', 'Mixed')], max_length=32)),
                ('form_key', models.SlugField(help_text='hotel_booking, rental_booking, salon_appointment...', max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('page_url', models.CharField(help_text='e.g. hotel-booking.html, rental-booking.html', max_length=200)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_forms', to='marketplace.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_forms', to='marketplace.businesscategory')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_forms', to='marketplace.industry')),
            ],
            options={
                'ordering': ['interaction_type', 'form_key'],
            },
        ),
    ]
