# Generated by Django 6.0.4 on 2026-06-26 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('payment', 'Payment Fraud'), ('account', 'Account Fraud'), ('order', 'Order Fraud')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(default=10, help_text='Risk score added when this rule triggers')),
                ('is_active', models.BooleanField(default=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric threshold for this rule (amount, count, etc)', max_digits=12, null=True)),
                ('time_window_minutes', models.IntegerField(default=60, help_text='Time window to check for this rule in minutes')),
            ],
            options={
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('payment', 'Payment Fraud'), ('account', 'Account Fraud'), ('order', 'Order Fraud')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('triggered_rules', models.JSONField(default=list, help_text='List of rule names that triggered this alert')),
                ('metadata', models.JSONField(default=dict, help_text='Extra context (IP, order_id, amount, etc)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('total_risk_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='cases', to='fraud.fraudalert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('ip', 'IP Address'), ('email', 'Email'), ('phone', 'Phone Number'), ('user', 'User Account'), ('device', 'Device ID')], max_length=20)),
                ('value', models.CharField(help_text='The blocked value (IP, email, phone, user_id)', max_length=255)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_blocked', models.BooleanField(default=False, help_text='True if system auto-blocked, False if admin manually blocked')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave null for permanent block', null=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entity_type', 'value')},
            },
        ),
    ]
