# Generated by Django 6.0.4 on 2026-06-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('commission_only', 'Commission Only'), ('subscription_only', 'Subscription Only'), ('hybrid', 'Hybrid')], default='commission_only', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allows_exclusive_bookings', models.BooleanField(default=False)),
                ('allows_slot_bookings', models.BooleanField(default=True)),
                ('allows_seat_bookings', models.BooleanField(default=True)),
                ('max_bookable_items', models.IntegerField(default=5)),
                ('max_monthly_bookings', models.IntegerField(default=0)),
                ('max_monthly_orders', models.IntegerField(default=0)),
                ('max_products', models.IntegerField(default=10)),
                ('max_staff', models.IntegerField(default=2)),
                ('trial_days', models.IntegerField(default=14)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='marketplace.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_subscriptions', to='subscriptions.businessplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial_started', 'Trial Started'), ('trial_converted', 'Trial Converted'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated')], max_length=20)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='marketplace.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.businessplan')),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downgrade_history', to='subscriptions.businessplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
