# Generated by Django 6.0.4 on 2026-06-18 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('subscriptions', '0002_businessplan_businesssubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='grace_period_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='supported_industries',
            field=models.ManyToManyField(blank=True, related_name='supported_plans', to='marketplace.industry'),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='current_monthly_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='current_monthly_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='current_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='current_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded'), ('limited', 'Limited'), ('addon', 'Available as Add-on')], default='included', max_length=10)),
                ('limit_value', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_highlight', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.businessplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('new', 'New Subscription'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('trial_conversion', 'Trial Conversion'), ('reactivation', 'Reactivation')], default='new', max_length=20)),
                ('gateway', models.CharField(choices=[('wallet', 'Wallet'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('bank_transfer', 'Bank Transfer'), ('admin', 'Admin Credit')], default='wallet', max_length=20)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='marketplace.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.businessplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.businesssubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
