# Generated by Django 6.0.4 on 2026-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_businessplan_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='custom_max_bookable_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='custom_max_monthly_bookings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='custom_max_monthly_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='custom_max_products',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='custom_max_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
