# Generated by Django 6.0.4 on 2026-07-17 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_bookableitemcategory_alter_bookableitem_category'),
        ('marketplace', '0016_alter_businesspromotion_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('promotion_type', models.CharField(choices=[('discount', 'Discount Code'), ('flash_sale', 'Flash Sale'), ('bundle', 'Bundle Deal'), ('free_delivery', 'Free Delivery'), ('referral', 'Referral'), ('loyalty', 'Loyalty Reward'), ('first_order', 'First Order'), ('booking_coupon', 'Booking Coupon')], max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_limit', models.IntegerField(default=0)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('total_uses', models.IntegerField(default=0)),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(blank=True, help_text='Blank = platform-wide promotion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Restrict to one bookable item. Blank = business-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='bookings.bookableitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
