# Generated by Django 6.0.4 on 2026-07-10 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('payments', '0002_paymentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('interaction_type', models.CharField(choices=[('order', 'Order'), ('booking', 'Booking'), ('service', 'Service'), ('appointment', 'Appointment'), ('scheduled_service', 'Scheduled Service'), ('ride', 'Ride'), ('shipment', 'Shipment'), ('transport', 'Transport')], max_length=30)),
                ('interaction_id', models.IntegerField(help_text='PK of the order/booking/ride etc.')),
                ('interaction_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('held', 'Held in Escrow'), ('released', 'Released to Vendor'), ('refunded', 'Refunded to Customer'), ('disputed', 'In Dispute'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='held', max_length=20)),
                ('release_trigger', models.CharField(blank=True, choices=[('delivery_otp', 'Delivery OTP Verified'), ('check_in', 'Check-in Code Verified'), ('completion_otp', 'Completion OTP Verified'), ('ride_start', 'Ride Start Code Verified'), ('ride_completed', 'Ride Completed'), ('boarding', 'Passenger Boarded'), ('auto_release', 'Auto-released After Deadline'), ('manual', 'Manually Released by Admin')], max_length=30, null=True)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, help_text='Funds auto-release at this time if no dispute', null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transactions', to='marketplace.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_payments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_transactions', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('trigger', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who triggered the transition', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.escrowtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['interaction_type', 'interaction_id'], name='payments_es_interac_4e3649_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='payments_es_status_d63b0b_idx'),
        ),
    ]
