# Generated by Django 6.0.4 on 2026-06-25 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_remove_currency_currency_code_and_more'),
        ('locations', '0002_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='currency',
            new_name='currency_code',
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='currencies.currency'),
        ),
    ]
