# Generated by Django 6.0.4 on 2026-05-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
        ('drivers', '0002_alter_vehicletype_options_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['city']},
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='payment_model',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='drivers.driverprofile'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dropoff_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_deliveries', to='locations.address'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dropoff_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_deliveries', to='locations.city'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dropoff_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_deliveries', to='locations.state'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dropoff_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_deliveries', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_deliveries', to='locations.address'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_deliveries', to='locations.city'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_deliveries', to='locations.state'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='dropoff_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='dropoff_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_deliveries', to='locations.zone'),
        ),
    ]
