# Generated by Django 6.0.4 on 2026-05-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliveryzone_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='dispatcher',
            new_name='driver',
        ),
    ]
