# Generated by Django 6.0.4 on 2026-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_rename_dispatcher_deliveryrequest_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='payment_model',
            field=models.CharField(blank=True, choices=[('marketplace', 'Marketplace'), ('logistics', 'Logistics')], default='marketplace', max_length=20, null=True),
        ),
    ]
