# Generated by Django 6.0.4 on 2026-06-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_deliveryrequest_payment_model'),
        ('orders', '0003_rename_shipping_fee_order_business_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='orders.order'),
        ),
    ]
