# Generated by Django 6.0.4 on 2026-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_deliveryrequest_arrived_at_pickup_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='arrived_at_dropoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='arriving_soon_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('at_pickup', 'Driver At Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_dropoff', 'Driver At Dropoff'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
