# Generated by Django 6.0.4 on 2026-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_deliveryrequest_arrived_at_dropoff_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
