# Generated by Django 6.0.4 on 2026-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='base_price_express',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='base_price_standard',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_type_icons/'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_weight_kg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='minimum_fare_express',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='minimum_fare_standard',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='per_kg_rate',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='slug',
            field=models.SlugField(default='General Zone', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='description',
            field=models.CharField(blank=True, default='General Zone', max_length=255),
            preserve_default=False,
        ),
    ]
