# Generated by Django 6.0.4 on 2026-07-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_vehicletype_options_and_more'),
        ('marketplace', '0010_shipmentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Ride/logistics company this driver belongs to. Null = independent platform driver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='marketplace.business'),
        ),
    ]
