# Generated by Django 6.0.4 on 2026-05-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('base_fare', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('max_passengers', models.IntegerField(default=4)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='vehicle_types/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['base_fare'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.TextField()),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver_current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('driver_current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('transfer', 'transfer')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching', 'Searching Driver'), ('accepted', 'Accepted'), ('driver_arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_driver', 'No Driver Found')], default='requested', max_length=20)),
                ('rider_rating', models.IntegerField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, null=True)),
                ('rider_review', models.TextField(blank=True, null=True)),
                ('driver_review', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='drivers.driverprofile')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.ridevehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='rides.ride')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
