# Generated by Django 6.0.4 on 2026-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_payment_method_transportbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_code',
            field=models.CharField(blank=True, help_text='Customer gives this code to driver before trip starts', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_code_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_code_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
