# Generated by Django 6.0.4 on 2026-07-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('rides', '0003_ride_start_code_ride_start_code_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Company page the ride was booked from. Null = marketplace-wide booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='marketplace.business'),
        ),
    ]
