# Generated by Django 6.0.4 on 2026-07-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='payment_method',
        ),
    ]
