# Generated by Django 6.0.4 on 2026-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('wallet', 'Wallet'), ('transfer', 'Transfer')], default='wallet', max_length=20),
        ),
    ]
