# Generated by Django 6.0.4 on 2026-07-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('rides', '0006_ride_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridevehicletype',
            name='business',
            field=models.ForeignKey(blank=True, help_text='None = platform-wide default available to all', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='ridevehicletype',
            name='vehicle_category',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('bus', 'Bus'), ('truck', 'Truck'), ('boat', 'Boat')], default='car', help_text='Global category for marketplace filtering', max_length=20),
        ),
    ]
