# Generated by Django 6.0.4 on 2026-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ridevehicletype_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridevehicletype',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
