# Generated by Django 6.0.4 on 2026-06-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('operations', '0002_maintenancetype_fleetvehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='marketplace.business'),
        ),
    ]
