# Generated by Django 6.0.4 on 2026-05-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='locations.address'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='locations.city'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='locations.state'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shipments', to='locations.address'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shipments', to='locations.city'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shipments', to='locations.state'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shipments', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
