# Generated by Django 6.0.4 on 2026-07-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('shipments', '0002_shipment_delivery_address_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Logistics business handling this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shipments/proof/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_signature',
            field=models.ImageField(blank=True, null=True, upload_to='shipments/signatures/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
