# Generated by Django 6.0.4 on 2026-07-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('shipments', '0003_shipment_business_shipment_declared_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentVehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_mode', models.CharField(choices=[('land', 'Land'), ('sea', 'Sea'), ('air', 'Air')], default='land', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Shipment Vehicle Categories',
                'ordering': ['transport_mode', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_vehicle_types', to='marketplace.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_types', to='shipments.shipmentvehiclecategory')),
            ],
            options={
                'verbose_name_plural': 'Shipment Vehicle Types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
