# Generated by Django 6.0.4 on 2026-07-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_shipmentsettings'),
        ('shipments', '0004_shipmentvehiclecategory_shipmentvehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('estimated_days_min', models.PositiveIntegerField(default=1)),
                ('estimated_days_max', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_service_categories', to='marketplace.business')),
            ],
            options={
                'verbose_name_plural': 'Shipment Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
