# Generated by Django 6.0.4 on 2026-06-18 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingcoupon_bookingguest_bookinginvoice_and_more'),
        ('commissions', '0002_commission_currency_commission_currency_symbol_and_more'),
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        ('orders', '0003_rename_shipping_fee_order_business_earnings_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_period_days', models.IntegerField(default=7)),
                ('auto_withdraw', models.BooleanField(default=False)),
                ('auto_withdraw_threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('frozen', 'Frozen')], default='active', max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_wallet', to='marketplace.business')),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_wallets', to='wallet.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('reserve', 'Reserve'), ('release', 'Release'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('settlement_due', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_transactions', to='bookings.booking')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_transactions', to='commissions.commission')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_transactions', to='orders.order')),
                ('vendor_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.vendorwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('insufficient_balance', 'Insufficient Balance'), ('invalid_bank_account', 'Invalid Bank Account'), ('suspicious_activity', 'Suspicious Activity'), ('pending_disputes', 'Pending Disputes'), ('kyc_required', 'KYC Verification Required'), ('other', 'Other')], max_length=30, null=True)),
                ('rejection_notes', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_withdrawals', to='wallet.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='marketplace.business')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('vendor_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.vendorwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarningsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_summaries', to='wallet.vendorwallet')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('vendor_wallet', 'period', 'period_start')},
            },
        ),
    ]
