# Generated by Django 6.0.4 on 2026-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_vendorwallet_vendortransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
