# Generated by Django 6.0.4 on 2026-06-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookableitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_mode', models.CharField(choices=[('exclusive', 'Exclusive'), ('slot_based', 'Slot Based'), ('seat_based', 'Seat Based')], default='exclusive', max_length=20)),
                ('slots_per_day', models.IntegerField(default=1)),
                ('slot_duration_minutes', models.IntegerField(default=60)),
                ('slots_start_time', models.TimeField(blank=True, null=True)),
                ('slots_end_time', models.TimeField(blank=True, null=True)),
                ('break_between_slots', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=1)),
                ('allow_same_day_checkout_checkin', models.BooleanField(default=True)),
                ('buffer_hours', models.IntegerField(default=0)),
                ('free_cancellation_hours', models.IntegerField(default=24)),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='bookings.bookableitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
