# Generated by Django 6.0.4 on 2026-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingcoupon_bookingguest_bookinginvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
