# Generated by Django 6.0.4 on 2026-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_checkin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableitem',
            name='requires_kyc',
            field=models.BooleanField(default=False, help_text='Require guest identity verification before booking'),
        ),
    ]
