# Generated by Django 6.0.4 on 2026-07-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookableitem_requires_kyc'),
        ('marketplace', '0010_shipmentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookable_item_categories', to='marketplace.business')),
            ],
            options={
                'verbose_name': 'Bookable Item Category',
                'verbose_name_plural': 'Bookable Item Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('business', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='bookableitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Business-scoped category (e.g. Standard Room, Suite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bookings.bookableitemcategory'),
        ),
    ]
