# Generated by Django 6.0.4 on 2026-08-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookableitemcategory_alter_bookableitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_id_number',
            field=models.ImageField(blank=True, help_text="Photo or scan of the guest's ID document — required only when BookingSettings.requires_guest_kyc is set.", null=True, upload_to='bookings/guest_ids/'),
        ),
    ]
