# Generated by Django 6.0.4 on 2026-07-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_subscriptionanalytics_promotionanalytics_and_more'),
        ('marketplace', '0015_business_mission_business_story_businesscontentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionanalytics',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_analytics', to='marketplace.business'),
        ),
    ]
