# Generated by Django 6.0.4 on 2026-07-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_promotionanalytics_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionanalytics',
            options={'verbose_name_plural': 'Promotion analytics'},
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='business',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='name',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='per_user_limit',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='promotion_type',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='total_discount_given',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='total_uses',
        ),
        migrations.RemoveField(
            model_name='promotionanalytics',
            name='usage_limit',
        ),
    ]
