# Generated by Django 6.0.4 on 2026-07-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_promotionanalytics_options_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionanalytics',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.promotion'),
        ),
    ]
