# Generated by Django 6.0.4 on 2026-07-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_promotionanalytics_promotion'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionanalytics',
            name='promotion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.promotion'),
            preserve_default=False,
        ),
    ]
