# Generated by Django 6.0.4 on 2026-06-27 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.CharField(choices=[('booking', 'Booking Verification'), ('vendor', 'Vendor Onboarding'), ('driver', 'Driver Verification'), ('general', 'General')], default='booking', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('auto_approved', 'Auto Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('sumsub_applicant_id', models.CharField(blank=True, help_text='Applicant ID from Sumsub', max_length=100, null=True)),
                ('sumsub_inspection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sumsub_correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sumsub_review_result', models.JSONField(blank=True, default=dict, help_text='Raw review result from Sumsub webhook')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejection_labels', models.JSONField(blank=True, default=list, help_text='Sumsub rejection labels')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='KYC validity expiry (null = never expires)', null=True)),
                ('risk_level', models.CharField(blank=True, help_text='Risk level from Sumsub', max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'use_case')},
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('nin', 'National ID (NIN)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('bvn', 'BVN'), ('selfie', 'Selfie / Liveness'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement')], max_length=30)),
                ('document_number', models.CharField(blank=True, help_text='NIN number, passport number, etc.', max_length=100, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='kyc_documents/')),
                ('sumsub_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_dob', models.DateField(blank=True, null=True)),
                ('extracted_expiry', models.DateField(blank=True, null=True)),
                ('country_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('auto_approved', 'Auto Approved'), ('auto_rejected', 'Auto Rejected'), ('manual_approved', 'Manually Approved'), ('manual_rejected', 'Manually Rejected'), ('resubmitted', 'Resubmitted'), ('expired', 'Expired'), ('webhook_received', 'Webhook Received')], max_length=30)),
                ('is_system_action', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='kyc.kycprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCSelfie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='kyc_selfies/')),
                ('sumsub_selfie_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('liveness_score', models.FloatField(blank=True, help_text='Liveness detection confidence score', null=True)),
                ('face_match_score', models.FloatField(blank=True, help_text='Face match score vs ID document', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to='kyc.kycprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
