# Generated by Django 6.0.4 on 2026-06-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_blacklisthistory_chargeback_fraudactionlog_and_more'),
        ('kyc', '0001_initial'),
        ('marketplace', '0002_permission_businessrole_businessstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sumsub_company_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('cac_certificate', 'CAC Certificate'), ('cac_status_report', 'CAC Status Report'), ('tin_certificate', 'TIN Certificate'), ('tax_clearance', 'Tax Clearance Certificate'), ('business_license', 'Business License'), ('memorandum', 'Memorandum of Association'), ('proof_of_address', 'Proof of Business Address'), ('bank_statement', 'Business Bank Statement'), ('director_id', 'Director ID')], max_length=30)),
                ('file', models.FileField(upload_to='business_kyc_documents/')),
                ('document_number', models.CharField(blank=True, help_text='CAC reg number, TIN number, etc.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='kyc_address_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=100)),
                ('max_retry_count', models.PositiveIntegerField(default=3)),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=90.0, help_text='Confidence score above which KYC is auto-approved', max_digits=5)),
                ('manual_review_threshold', models.DecimalField(decimal_places=2, default=65.0, help_text='Score below this triggers manual review', max_digits=5)),
                ('kyc_expiry_days', models.PositiveIntegerField(default=365, help_text='Days before KYC expires (0 = never)')),
                ('supported_countries', models.JSONField(default=list, help_text='ISO country codes supported e.g. ["NG", "GH"]')),
                ('require_selfie', models.BooleanField(default=True)),
                ('require_id_document', models.BooleanField(default=True)),
                ('require_address', models.BooleanField(default=False)),
                ('require_business_docs', models.BooleanField(default=False)),
                ('kyc_version', models.CharField(default='v1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('consent_version', models.CharField(default='v1', help_text='Version of consent terms accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True, help_text='Exact text the user agreed to')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCDuplicateIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('confidence', models.FloatField(default=100.0)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('nin', 'National ID (NIN)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('bvn', 'BVN'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('cac', 'CAC Certificate'), ('tin', 'TIN Certificate')], max_length=30)),
                ('document_hash', models.CharField(help_text='SHA256 hash of document number', max_length=64, unique=True)),
                ('document_number_masked', models.CharField(blank=True, help_text='Last 4 digits only e.g. ****1234', max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='Face match confidence score 0-100')),
                ('passed', models.BooleanField(default=False)),
                ('method', models.CharField(default='sumsub', help_text='Which service performed the match', max_length=50)),
                ('raw_result', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.CharField(choices=[('booking', 'Booking'), ('vendor', 'Vendor'), ('driver', 'Driver'), ('general', 'General')], max_length=20, unique=True)),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types e.g. ["nin", "selfie", "utility_bill"]')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['use_case'],
            },
        ),
        migrations.CreateModel(
            name='KYCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('documents_uploaded', 'Documents Uploaded'), ('selfie_uploaded', 'Selfie Uploaded'), ('submitted', 'Submitted for Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sumsub_sdk_token', models.CharField(blank=True, max_length=500, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist_type', models.CharField(choices=[('pep', 'Politically Exposed Person'), ('sanction', 'Sanctions List'), ('aml', 'AML Watchlist'), ('terrorist', 'Terrorist List'), ('adverse_media', 'Adverse Media')], max_length=20)),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('potential_match', 'Potential Match'), ('confirmed_match', 'Confirmed Match'), ('false_positive', 'False Positive')], default='clear', max_length=20)),
                ('matched', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, help_text='Match confidence score 0-100', null=True)),
                ('source', models.CharField(blank=True, help_text='Which watchlist source e.g. UN, OFAC, EU', max_length=100)),
                ('match_details', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('sumsub', 'Sumsub'), ('manual', 'Manual')], default='sumsub', max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('applicant_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Verification confidence percentage from Sumsub', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Admin-only notes, never shown to customer', null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='kyc_version',
            field=models.CharField(default='v1', max_length=20),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='last_webhook',
            field=models.JSONField(blank=True, default=dict, help_text='Last raw webhook payload from Sumsub'),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verification_method',
            field=models.CharField(choices=[('sumsub', 'Sumsub'), ('manual', 'Manual'), ('government_api', 'Government API')], default='sumsub', max_length=20),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycreviewlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycreviewlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycselfie',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycselfie',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('nin', 'National ID (NIN)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('bvn', 'BVN'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('cac', 'CAC Certificate'), ('tin', 'TIN Certificate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Supports images and PDFs', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='rejection_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('auto_approved', 'Auto Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='sumsub_applicant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='sumsub_review_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kycreviewlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('auto_approved', 'Auto Approved'), ('auto_rejected', 'Auto Rejected'), ('manual_approved', 'Manually Approved'), ('manual_rejected', 'Manually Rejected'), ('resubmitted', 'Resubmitted'), ('expired', 'Expired'), ('webhook_received', 'Webhook Received'), ('consent_given', 'Consent Given'), ('duplicate_detected', 'Duplicate Detected'), ('watchlist_flagged', 'Watchlist Flagged')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycselfie',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycselfie',
            name='liveness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('kyc_profile', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['document_type'], name='kyc_kycdocu_documen_106ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['status'], name='kyc_kycdocu_status_91d83a_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['user'], name='kyc_kycprof_user_id_0382c3_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['status'], name='kyc_kycprof_status_7fdb68_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['use_case'], name='kyc_kycprof_use_cas_b9d9cc_idx'),
        ),
        migrations.AddField(
            model_name='businesskyc',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_kyc', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='businesskyc',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesskyc',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_kyc_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesskycdocument',
            name='business_kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.businesskyc'),
        ),
        migrations.AddField(
            model_name='kycaddress',
            name='kyc_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycconsent',
            name='kyc_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycduplicateidentity',
            name='fraud_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_identities', to='fraud.fraudalert'),
        ),
        migrations.AddField(
            model_name='kycduplicateidentity',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duplicates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycduplicateidentity',
            name='users',
            field=models.ManyToManyField(related_name='duplicate_identity_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycidentity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='kyc_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycduplicateidentity',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='kyc.kycidentity'),
        ),
        migrations.AddField(
            model_name='kycmatch',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='kyc.kycdocument'),
        ),
        migrations.AddField(
            model_name='kycmatch',
            name='kyc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycmatch',
            name='selfie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='kyc.kycselfie'),
        ),
        migrations.AddField(
            model_name='kycsession',
            name='kyc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycwatchlist',
            name='kyc_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_checks', to='kyc.kycprofile'),
        ),
        migrations.AddField(
            model_name='kycwatchlist',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycwebhook',
            name='kyc_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='kyc.kycprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='businesskycdocument',
            unique_together={('business_kyc', 'document_type')},
        ),
    ]
