# Generated by Django 6.0.4 on 2026-08-08 09:26

import apps.idempotency.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('request_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.idempotency.models.default_expiry)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'user', 'endpoint'], name='idempotency_key_953696_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user', 'endpoint'), name='unique_idempotency_key_scope')],
            },
        ),
    ]
