# Generated by Django 6.0.4 on 2026-06-09 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='objects_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_type',
            new_name='objects_type',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'objects_id', 'objects_type')},
        ),
    ]
