# Generated by Django 6.0.4 on 2026-07-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('marketplace', '0010_shipmentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appointments/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_categories', to='marketplace.business')),
            ],
            options={
                'verbose_name_plural': 'Appointment categories',
                'ordering': ['order', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='appointments.appointmentcategory'),
        ),
    ]
