# Generated by Django 6.0.4 on 2026-08-04 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentcategory_appointmentservice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('file', 'File upload')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Dropdown choices only, e.g. ["Short", "Medium", "Long"]', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='appointments.appointmentservice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
