# Generated by Django 6.0.4 on 2026-08-08 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('bookable', 'Bookable Item'), ('service', 'Service'), ('appointment', 'Appointment'), ('business', 'Business'), ('route', 'Transport Route')], default='product', max_length=50),
        ),
        migrations.CreateModel(
            name='WishlistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wishlist.wishlistcollection'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'item_id', 'item_type'), name='unique_user_wishlist_item'),
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_type',
        ),
        migrations.AddConstraint(
            model_name='wishlistcollection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_wishlist_collection'),
        ),
    ]
